spring:
  mail:
    host: imap.gmail.com
    port: 587
    username: salmansiddiqui100@gmail.com
    password: drsalman12@
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: imap.gmail.com

  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/salmonitoring
      username: root
      password: Mpasas1109123@
  jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
